
export const currencies = [{currencyISO:"AFN",CurrencyName:"Afghani",Symbol:"؋"},
{currencyISO:"THB",CurrencyName:"Baht",Symbol:"฿"},
{currencyISO:"PAB",CurrencyName:"Balboa",Symbol:"B"},
{currencyISO:"ETB",CurrencyName:"Birr Etiopía",Symbol:"B"},
{currencyISO:"VEF",CurrencyName:"Bolivar Fuerte",Symbol:"B"},
{currencyISO:"BOB",CurrencyName:"Boliviano",Symbol:"B"},
{currencyISO:"BND",CurrencyName:"Brunei Dólar",Symbol:"B"},
{currencyISO:"GHS",CurrencyName:"Cedi",Symbol:"G"},
{currencyISO:"CRC",CurrencyName:"Colón Costa Rican",Symbol:"₡"},
{currencyISO:"SVC",CurrencyName:"Colón Salvadoreño",Symbol:"₡"},
{currencyISO:"NIO",CurrencyName:"Cordoba Oro",Symbol:"C"},
{currencyISO:"DKK",CurrencyName:"Corona Danesa",Symbol:"K"},
{currencyISO:"ISK",CurrencyName:"Corona Islandia",Symbol:"k"},
{currencyISO:"NOK",CurrencyName:"Corona Noruega",Symbol:"k"},
{currencyISO:"SEK",CurrencyName:"Corona Suiza",Symbol:"k"},
{currencyISO:"GMD",CurrencyName:"Dalasi",Symbol:"D"},
{currencyISO:"MKD",CurrencyName:"Dinar",Symbol:"д"},
{currencyISO:"DZD",CurrencyName:"Dinar Algeria",Symbol:"د"},
{currencyISO:"BHD",CurrencyName:"Dinar Bahrainí",Symbol:"."},
{currencyISO:"LYD",CurrencyName:"Dinar de Libia",Symbol:"ل"},
{currencyISO:"RSD",CurrencyName:"Dinar de Serbian",Symbol:"д"},
{currencyISO:"TND",CurrencyName:"Dinar de Tunisia",Symbol:"د"},
{currencyISO:"IQD",CurrencyName:"Dinar Iraqi",Symbol:"ع"},
{currencyISO:"JOD",CurrencyName:"Dinar Jordano",Symbol:"د"},
{currencyISO:"KWD",CurrencyName:"Dinar Kuwaití",Symbol:"د"},
{currencyISO:"MAD",CurrencyName:"Dirham de Moroco",Symbol:"د"},
{currencyISO:"DJF",CurrencyName:"Djibouti Franco",Symbol:"F"},
{currencyISO:"STD",CurrencyName:"Dobra",Symbol:"D"},
{currencyISO:"USD",CurrencyName:"Dólar Americano",Symbol:"$"},
{currencyISO:"AUD",CurrencyName:"Dólar Australiano",Symbol:"$"},
{currencyISO:"BSD",CurrencyName:"Dólar Bahamas",Symbol:"B"},
{currencyISO:"BBD",CurrencyName:"Dólar Barbados",Symbol:"B"},
{currencyISO:"BZD",CurrencyName:"Dólar Belize",Symbol:"B"},
{currencyISO:"BMD",CurrencyName:"Dólar Bremuda",Symbol:"B"},
{currencyISO:"CAD",CurrencyName:"Dólar Canadiense",Symbol:"$"},
{currencyISO:"GYD",CurrencyName:"Dólar de Guyana",Symbol:"G"},
{currencyISO:"NAD",CurrencyName:"Dólar de Namibia",Symbol:"N"},
{currencyISO:"ZWL",CurrencyName:"Dólar de Zimbabwe",Symbol:"$"},
{currencyISO:"XCD",CurrencyName:"Dólar del Este Caribeño",Symbol:"E"},
{currencyISO:"FJD",CurrencyName:"Dólar Fiji",Symbol:"F"},
{currencyISO:"HKD",CurrencyName:"Dólar Hong Kong",Symbol:"H"},
{currencyISO:"KYD",CurrencyName:"Dólar Islas Caimán",Symbol:"$"},
{currencyISO:"SBD",CurrencyName:"Dólar Islas Salomón",Symbol:"S"},
{currencyISO:"JMD",CurrencyName:"Dólar Jamaiquino",Symbol:"$"},
{currencyISO:"LRD",CurrencyName:"Dólar Liberiano",Symbol:"L"},
{currencyISO:"NZD",CurrencyName:"Dólar Nueva Zelanda",Symbol:"$"},
{currencyISO:"SGD",CurrencyName:"Dólar Singapur",Symbol:"S"},
{currencyISO:"SRD",CurrencyName:"Dólar Surinam",Symbol:"$"},
{currencyISO:"TWD",CurrencyName:"Dólar Taiwanés",Symbol:"$"},
{currencyISO:"TTD",CurrencyName:"Dólar Trinidad y Tobago",Symbol:"$"},
{currencyISO:"VND",CurrencyName:"Dong",Symbol:"₫"},
{currencyISO:"AMD",CurrencyName:"Dram Armenio",Symbol:"դ"},
{currencyISO:"CVE",CurrencyName:"Escudo Cabo Verde",Symbol:"E"},
{currencyISO:"EUR",CurrencyName:"Euro",Symbol:"€"},
{currencyISO:"HUF",CurrencyName:"Florín Húgaro",Symbol:"F"},
{currencyISO:"XAF",CurrencyName:"Franco CFA",Symbol:"C"},
{currencyISO:"XOF",CurrencyName:"Franco CFA",Symbol:"C"},
{currencyISO:"XPF",CurrencyName:"Franco CFA",Symbol:"F"},
{currencyISO:"CDF",CurrencyName:"Franco Congolés",Symbol:"F"},
{currencyISO:"KMF",CurrencyName:"Franco de Comoro",Symbol:"F"},
{currencyISO:"GNF",CurrencyName:"Franco de Guinea",Symbol:"F"},
{currencyISO:"RWF",CurrencyName:"Franco Ruandés",Symbol:"R"},
{currencyISO:"CHF",CurrencyName:"Franco Suizo",Symbol:"F"},
{currencyISO:"BIF",CurrencyName:"Francoo de Burundi",Symbol:"F"},
{currencyISO:"HTG",CurrencyName:"Gourde",Symbol:"G"},
{currencyISO:"PYG",CurrencyName:"Guarani",Symbol:"₲"},
{currencyISO:"ANG",CurrencyName:"Guilder Antillas Nerlandesas",Symbol:"N"},
{currencyISO:"AWG",CurrencyName:"Guilder de Aruba",Symbol:"A"},
{currencyISO:"UAH",CurrencyName:"Hryvnia",Symbol:"₴"},
{currencyISO:"PGK",CurrencyName:"Kina",Symbol:"K"},
{currencyISO:"LAK",CurrencyName:"Kip",Symbol:"₭"},
{currencyISO:"CZK",CurrencyName:"Koruna Checa",Symbol:"K"},
{currencyISO:"EEK",CurrencyName:"Kroon",Symbol:"K"},
{currencyISO:"HRK",CurrencyName:"Kuna Croatí",Symbol:"k"},
{currencyISO:"MWK",CurrencyName:"Kwacha",Symbol:"M"},
{currencyISO:"ZMK",CurrencyName:"Kwacha de Zambia",Symbol:"Z"},
{currencyISO:"AOA",CurrencyName:"Kwanza",Symbol:"K"},
{currencyISO:"MMK",CurrencyName:"Kyat",Symbol:"K"},
{currencyISO:"GEL",CurrencyName:"Lari",Symbol:"l"},
{currencyISO:"LVL",CurrencyName:"Latvian Lats",Symbol:"L"},
{currencyISO:"ALL",CurrencyName:"Lek",Symbol:"L"},
{currencyISO:"HNL",CurrencyName:"Lempira",Symbol:"L"},
{currencyISO:"SLL",CurrencyName:"Leone",Symbol:"L"},
{currencyISO:"MDL",CurrencyName:"Leu de Moldovia",Symbol:"l"},
{currencyISO:"BGN",CurrencyName:"Lev Búlgaro",Symbol:"л"},
{currencyISO:"SHP",CurrencyName:"Libra de Santa Eelena",Symbol:"£"},
{currencyISO:"SDG",CurrencyName:"Libra de Sudán",Symbol:"£"},
{currencyISO:"EGP",CurrencyName:"Libra Egipcia",Symbol:"£"},
{currencyISO:"GIP",CurrencyName:"Libra Gibraltar",Symbol:"£"},
{currencyISO:"FKP",CurrencyName:"Libra Islas Falkland",Symbol:"£"},
{currencyISO:"LBP",CurrencyName:"Libra Libanesa",Symbol:"ل"},
{currencyISO:"SYP",CurrencyName:"Libra Siria",Symbol:"S"},
{currencyISO:"GBP",CurrencyName:"Libra Sterling",Symbol:"£"},
{currencyISO:"SZL",CurrencyName:"Lilangeni",Symbol:"L"},
{currencyISO:"TRY",CurrencyName:"Lira Turca",Symbol:"T"},
{currencyISO:"LTL",CurrencyName:"Litas Lutianesa",Symbol:"L"},
{currencyISO:"LSL",CurrencyName:"Loti",Symbol:"L"},
{currencyISO:"MGA",CurrencyName:"Malagasy Ariary",Symbol:"F"},
{currencyISO:"TMT",CurrencyName:"Manat",Symbol:"m"},
{currencyISO:"AZN",CurrencyName:"Manat Azerbaijanian",Symbol:"м"},
{currencyISO:"BAM",CurrencyName:"Marcos Convertibles",Symbol:"K"},
{currencyISO:"MZN",CurrencyName:"Metical",Symbol:"M"},
{currencyISO:"NGN",CurrencyName:"Naira",Symbol:"₦"},
{currencyISO:"ERN",CurrencyName:"Nakfa",Symbol:"N"},
{currencyISO:"BTN",CurrencyName:"Ngultrum",Symbol:"N"},
{currencyISO:"RON",CurrencyName:"Nuevo Leu",Symbol:"L"},
{currencyISO:"PEN",CurrencyName:"Nuevo Sol",Symbol:"S"},
{currencyISO:"MRO",CurrencyName:"Ouguiya",Symbol:"U"},
{currencyISO:"TOP",CurrencyName:"Pa'anga",Symbol:"T"},
{currencyISO:"MOP",CurrencyName:"Pataca",Symbol:"M"},
{currencyISO:"ARS",CurrencyName:"Peso Argentino",Symbol:"$"},
{currencyISO:"CLP",CurrencyName:"Peso Chileno",Symbol:"$"},
{currencyISO:"COP",CurrencyName:"Peso Colombiano",Symbol:"C"},
{currencyISO:"CUP",CurrencyName:"Peso Cubano",Symbol:"$"},
{currencyISO:"DOP",CurrencyName:"Peso Dominicano",Symbol:"R"},
{currencyISO:"PHP",CurrencyName:"Peso Filipino",Symbol:"₱"},
{currencyISO:"GWP",CurrencyName:"Peso Guinea-Bissau",Symbol:"$"},
{currencyISO:"MXN",CurrencyName:"Peso Mexicano",Symbol:"$"},
{currencyISO:"UYU",CurrencyName:"Peso Uruguayo",Symbol:"$"},
{currencyISO:"BWP",CurrencyName:"Pula",Symbol:"P"},
{currencyISO:"QAR",CurrencyName:"Qatari Rial",Symbol:"ر"},
{currencyISO:"GTQ",CurrencyName:"Quetzal",Symbol:"Q"},
{currencyISO:"ZAR",CurrencyName:"Rand",Symbol:"R"},
{currencyISO:"BRL",CurrencyName:"Real Brasileño",Symbol:"R"},
{currencyISO:"IRR",CurrencyName:"Rial Iraní",Symbol:"﷼"},
{currencyISO:"OMR",CurrencyName:"Rial Omani",Symbol:"ر"},
{currencyISO:"YER",CurrencyName:"Rial Yemení",Symbol:"ر"},
{currencyISO:"KHR",CurrencyName:"Riel",Symbol:"r"},
{currencyISO:"MYR",CurrencyName:"Ringgit de Malasia",Symbol:"R"},
{currencyISO:"SAR",CurrencyName:"Riyal Saudí",Symbol:"ر"},
{currencyISO:"BYR",CurrencyName:"Rublo Bieloruso",Symbol:"B"},
{currencyISO:"RUB",CurrencyName:"Rublo Ruso",Symbol:"р"},
{currencyISO:"MVR",CurrencyName:"Rufiyaa",Symbol:"R"},
{currencyISO:"IDR",CurrencyName:"Rupia",Symbol:"R"},
{currencyISO:"SCR",CurrencyName:"Rupia de Seychelles",Symbol:"S"},
{currencyISO:"INR",CurrencyName:"Rupia Indú",Symbol:"R"},
{currencyISO:"MUR",CurrencyName:"Rupia Mauritius",Symbol:"R"},
{currencyISO:"NPR",CurrencyName:"Rupia Nepalesa",Symbol:"N"},
{currencyISO:"PKR",CurrencyName:"Rupia Pakistaní",Symbol:"R"},
{currencyISO:"LKR",CurrencyName:"Rupia Sri Lanka",Symbol:"R"},
{currencyISO:"ILS",CurrencyName:"Sheqel Israeli",Symbol:"₪"},
{currencyISO:"TZS",CurrencyName:"Shilling de Tanzania",Symbol:"\/"},
{currencyISO:"UGX",CurrencyName:"Shilling de Uganda",Symbol:"U"},
{currencyISO:"KES",CurrencyName:"Shilling Kenya",Symbol:"K"},
{currencyISO:"SOS",CurrencyName:"Shilling Somalí",Symbol:"S"},
{currencyISO:"KGS",CurrencyName:"Som",Symbol:"с"},
{currencyISO:"TJS",CurrencyName:"Somoni",Symbol:"С"},
{currencyISO:"UZS",CurrencyName:"Sum Uzbekistán",Symbol:"с"},
{currencyISO:"BDT",CurrencyName:"Taka",Symbol:"৳"},
{currencyISO:"WST",CurrencyName:"Tala",Symbol:"W"},
{currencyISO:"KZT",CurrencyName:"Tenge",Symbol:"〒"},
{currencyISO:"MNT",CurrencyName:"Tugrik",Symbol:"₮"},
{currencyISO:"AED",CurrencyName:"UAE Dirham",Symbol:"د"},
{currencyISO:"VUV",CurrencyName:"Vatu",Symbol:"V"},
{currencyISO:"KRW",CurrencyName:"Won",Symbol:"₩"},
{currencyISO:"KPW",CurrencyName:"Won Nor-Coreano",Symbol:"₩"},
{currencyISO:"JPY",CurrencyName:"Yen Japonés",Symbol:"¥"},
{currencyISO:"CNY",CurrencyName:"Yuan Chino",Symbol:"¥"},
{currencyISO:"PLN",CurrencyName:"Zloty Polaco",Symbol:"z"}]
